# Build settings
permalink: /blog/:year/:title/
markdown: kramdown
highlighter: pygments
plugins: [jekyll-paginate-v2]

pagination:
  enabled: true
  per_page: 3
  permalink: "/page/:num/"

comments: true

source: source
destination: _site
sass:
  sass_dir: _sass
  style: compressed # expanded

# SEO settings
title: Yasemin CIRT 
description: "Blockchain Engineer"
keywords: "blockchain, crypto, engineer, bitcoin, ethereum, dapp, contract"
url: http://yasemincirt.github.io
baseurl: "yasemincirt.github.io"

google_analytics: UA-52446115-1
repo: http://github.com/nandomoreirame/end2end
disqus_shortname: "nandothemes"
disqus_site_shortname: "nandothemes"

# Author settings
author:
  name: Yasemin CIRT
  job: Blockchain Engineer
  bio: "blockchain engineer @Icrypex, director of technology @istbcw, solidity lover, ethereum application developer"
  thumb: /images/author.jpg
  email: yasemincirt@gmail.com
  url: https://yasemincirt.github.io/
  github: https://github.com/yasemincirt
  twitter: https://twitter.com/yasemincirt
  facebook:
  linkedin: https://linkedin.com/in/yasemincirt

# navbar pages
navbar:
  - slug: about
    title: About
  - slug: icons
    title: Icons
  - slug: blog
    title: Blog

exclude: ["config.rb", "src", "Gemfile", "Gemfile.lock", "package.json","README.md", "Rakefile"]
